### ISSUE TITLE
Error: Openai not being acknowledged, could be an issue with Conda

### ISSUE THREAD

**Issue by Gorbixing** [EnkrateiaLucca/summarization_with_langchain#1]
I've tried opening the streeamlit app from my private repo with a clone of your repo. 

This is the error I've encountered. 

It's unusual considering openai is definitely in the requirements.txt. 

Additionally, I've tried running the app straight from my terminal but there are select Conda packages which won't install, even manually. 

GPT mentions it may be because the app is suited for a Linux environment and not a Windows environment. 

In any event, thanks for your hard work. 

"/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
File "/app/custom-summarization-app/custom_summarization_app_streamlit_version.py", line 1, in <module>
    import openai

**Comment by EnkrateiaLucca** [comment]
I did only run it on Linux
